### ISSUE TITLE
Problem with my PC can you help??

### ISSUE THREAD

**Issue by Dessant56** [Nirj2004/WhatsApp-SpammerBot#2]
Sir, my PC crashed and I turned it off. After sometime I turned it on, the fans are working but display not coming and displaying no signal. 
PLEASE HELP 🥺🥺🥺

**Comment by Nirj2004** [comment]
I don't think the problem caused to you is due to the repository.
If you need any other help regarding anything related to your mentioned
problem, please contact me  on ***@***.***
By the way, if you can then try switching the ram slots.

KEEP CODING!!!

**Comment by Nirj2004** [comment]
I don't think the problem caused to you is due to the repository. 
If you need any other help regarding anything related to your mentioned problem, please contact me  on [nirjharbiswas2021@protonmail.com](mailto:nirjharbiswas2021@protonmail.com)
By the way, if you can then try switching the ram slots.

KEEP CODING!!!

**Comment by Dessant56** [comment]
Can you please send me your contact number??

**Comment by Nirj2004** [comment]
I'm sorry I can't help you with that.

**Comment by Nirj2004** [comment]
Sorry I can't help you with that.
